server:
    port: 8080

spring:
  application:
    name: survey
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:7080/realms/master
  datasource:
    url: jdbc:postgresql://host.docker.internal:15432/postgres
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: create
  data:
    jpa:
      repositories:
        enabled: true
