services:
  database:
    image: 'postgres:latest'
    ports:
      - 15432:5432
    environment:
      POSTGRES_USER: username # The PostgreSQL user (useful to connect to the database)
      POSTGRES_PASSWORD: password # The PostgreSQL password (useful to connect to the database)
    networks:
      - postgres-network
    volumes:
      - ${PWD}/db-data/:/var/lib/postgresql/data/
      - ${PWD}/init.sql:/docker-entrypoint-initdb.d/init.sql

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 15480:80
    environment:
      PGADMIN_DEFAULT_EMAIL: jeffrey@defjef.nl
      PGADMIN_DEFAULT_PASSWORD: Jeffm@n1234
    depends_on:
      - database
    networks:
      - postgres-network
    volumes:
      - ${PWD}/pgadmin-data/:/var/lib/pgadmin/

  kc-database: # Example. Remove before using.
    image: postgres:latest
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - "15433:5432"
    networks:
      - postgres-network

  keycloak:
    image: quay.io/keycloak/keycloak:26.0
    environment:
      KC_HOSTNAME: host.docker.internal
      KC_HOSTNAME_PORT: 7080
      KC_HOSTNAME_STRICT_BACKCHANNEL: "true"
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HEALTH_ENABLED: "true"
      KC_LOG_LEVEL: info
    healthcheck:
      test: ["CMD", "curl", "-f", "http://host.docker.internal:7080/health/ready"]
      interval: 15s
      timeout: 2s
      retries: 15
    command: ["start-dev", "--http-port", "7080", "--https-port", "7443", "--import-realm"]
    volumes: # Ignore if you don't have realm-export.json to migrate data
      - ../keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    ports:
      - "7080:7080"
      - "7443:7443"
    networks:
      - postgres-network

networks:
  postgres-network:
    driver: bridge
