server:
  port: 8082

spring:
  application:
    name: admin
  datasource:
    url: jdbc:postgresql://host.docker.internal:15432/postgres
    username: username
    password: password
  jpa:
    hibernate:
      ddl-auto: update
